name: Activity Box

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: JasonEtco/activity-box@master
        env:
          GH_PAT: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: Jeve-Stobs
          GIST_ID: ae056e79be0c8a9c21c0d83f8fd847e8
